name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile: ['base', 'web-dev', 'another-container']

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Paths filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          modified: '.devcontainer/${{ matrix.dockerfile }}/Dockerfile'

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_REGISTRY_RW }}

    - name: Build and push Docker image
      if: steps.filter.outputs.modified == 'true'
      uses: docker/build-push-action@v2
      with:
        context: .devcontainer/${{ matrix.dockerfile }}
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/codespaces-${{ matrix.dockerfile }}:latest