name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: ['base', 'web-dev'] # Add other configurations as needed
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_REGISTRY_RW }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .devcontainer/${{ matrix.config }}
        file: .devcontainer/${{ matrix.config }}/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/codespaces-${{ matrix.config }}:latest
