name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/base/**'
      - '.devcontainer/large/**'
      - '.devcontainer/web-dev/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dockerfile: ['base', 'large', 'web-dev']
      fail-fast: false

    steps:
    - name: Check out code
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2 # Assuming v2 is the latest version
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_REGISTRY_RW }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3 # Assuming v3 is the latest version
      with:
        context: .devcontainer/${{ matrix.dockerfile }}
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/codespaces-${{ matrix.dockerfile }}:latest
