name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - '.devcontainer/**'

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Find Docker configurations
      id: set-matrix
      run: |
        CONFIG_DIRS=$(find .devcontainer -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | grep -v '^base$')
        echo "Found configurations: $CONFIG_DIRS"
        JSON_ARRAY=$(echo $CONFIG_DIRS | jq -R -s -c 'split(" ")')
        echo "::set-output name=matrix::{\"config\": $JSON_ARRAY}"

  build-and-push-base:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_REGISTRY_RW }}
    - name: Build and push base Docker image
      uses: docker/build-push-action@v3
      with:
        context: .devcontainer/base
        file: .devcontainer/base/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/codespaces-base:latest

  build-and-push-others:
    needs: [prepare-matrix, build-and-push-base]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.prepare-matrix.outputs.matrix)}}
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGE_REGISTRY_RW }}
    - name: Echo matrix config
      run: |
        echo "Building image for configuration: ${{ matrix.config }}"
    - name: Build and push other Docker images
      uses: docker/build-push-action@v3
      with:
        context: .devcontainer/${{ matrix.config }}
        file: .devcontainer/${{ matrix.config }}/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/codespaces-${{ matrix.config }}:latest
